CREATE TABLE IF NOT EXISTS ec2 (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  state TEXT,
  notification_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS chat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  role TEXT,
  content TEXT
);
