[ec2]
region = "REGION"
profile = "PROFILE"
check_every = 60
soft_checks = 3
notify_every = 2 # hours

[tg]
token = "TOKEN"
my_user_id = 0 # replace with your user ID

[du]
notify_at = 90
notify_every = 18 # hours

[chat]
api_key = "API_KEY"
model = "MODEL"
temperature = 1
system_prompt = "You are my personal bot. You prefer brief, to-the-point answers."
context = 8
clean = 1024
