[aws]
region = "REGION"
profile = "PROFILE"

[tg]
token = "TOKEN"
my_user_id = USER_ID

[du]
notify_at = 90
notify_every = 7200

[chat]
api_key = "API_KEY"
model = "MODEL"
temperature = 1
system_prompt = "You are my personal bot. You prefer brief, to-the-point answers and help me with stupid questions."
