[tool.poetry]
name = "dbot"
authors = ["Harry Wheildon"]
description = "dbot TG bot"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.33.10"
openai = "^1.3.7"
python-telegram-bot = { extras = ["job-queue"], version = "^20.7" }
